// styles/createMarkerModalStyles.js
export const modalStyles = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '24px',
    width: '90vw',
    maxWidth: '800px',
    height: '90vh',
    maxHeight: '700px',
    overflowY: 'auto',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  header: {
    marginBottom: '1px',
    paddingBottom: '10px',
    borderBottom: '1px solid #e5e7eb',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {
    display: 'flex',
    flexDirection: 'column',
  },
  headerRight: {
    display: 'flex',
    gap: '12px',
    marginTop: '4px',
  },
  title: {
    fontSize: '20px',
    fontWeight: '600',
    color: '#1f2937',
    margin: 0,
  },
  subtitle: {
    fontSize: '14px',
    color: '#6b7280',
    marginTop: '4px',
  },
  errorMessage: {
    backgroundColor: '#fef2f2',
    color: '#dc2626',
    padding: '12px',
    borderRadius: '6px',
    fontSize: '14px',
    marginBottom: '16px',
    border: '1px solid #fecaca',
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  titleRow: {
    display: 'flex',
    flexDirection: 'row',
    gap: '16px',
    alignItems: 'flex-start',
  },
  textFieldsColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    flex: 1,
  },
  iconsContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '8px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  inputField: {
    padding: '12px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    fontSize: '14px',
    fontFamily: 'inherit',
    outline: 'none',
    transition: 'border-color 0.2s ease',
    resize: 'none',
  },
  datePickerContainer: {
    display: 'flex',
    flexDirection: 'row',
    gap: '16px',
    alignItems: 'flex-start',
    minWidth: '300px',
  },
  dateTypeContainer: {
    display: 'flex',
    alignItems: 'flex-start',
    minWidth: '80px',
  },
  dateFieldsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    alignItems: 'flex-start',
    flex: 1,
  },
  dateTypeSelect: {
    padding: '4px 6px',
    border: '1px solid #d1d5db',
    borderRadius: '4px',
    fontSize: '11px',
    width: '80px',
    height: '26px',
    backgroundColor: 'white',
    cursor: 'pointer',
  },
  dateInputsContainer: {
    minHeight: '56px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    alignItems: 'flex-start',
    width: '100%',
  },
  dateRangeContainer: {
    display: 'flex',
    height: '56px',
    flexDirection: 'column',
    gap: '4px',
    alignItems: 'flex-start',
    width: '110px',
  },
  dateDisplay: {
    fontSize: '10px',
    color: '#6b7280',
    fontStyle: 'italic',
    textAlign: 'left',
    width: '100%',
    minHeight: '14px',
    marginLeft: '15px',
    marginTop: '5px',
  },
  dateSeparator: {
    color: '#6b7280',
    fontSize: '14px',
    textAlign: 'center',
    margin: '2px 0',
  },
  yearInput: {
    width: '60px',
    height: '26px',
    padding: '4px 6px',
    borderRadius: '4px',
    fontSize: '11px',
  },
  dateInput: {
    width: '110px',
    height: '26px',
    padding: '4px 6px',
    borderRadius: '4px',
    fontSize: '11px',
  },
};